# Generated by Django 6.0 on 2025-12-28 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal_app', '0003_alter_applyjobmodel_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobseekermodel',
            old_name='contact_numer',
            new_name='contact_number',
        ),
        migrations.AlterField(
            model_name='applyjobmodel',
            name='status',
            field=models.CharField(choices=[('Rejected', 'Rejected'), ('Pending', 'Pending'), ('Shortlisted', 'Shortlisted')], default='Pending', max_length=20, null=True),
        ),
    ]
